# Change these first
owner: hexadecimalDinosaur # Your GitHub organization or username, where this repository lives
repo: status.ivyfanchiang.ca # The name of this repository

sites:
  - name: Home: ivyfanchiang.ca
    url: https://ivyfanchiang.ca
  #- name: NextCloud
  #  url: https://nc.ivyfanchiang.ca/ocs/v2.php/apps/serverinfo/api/v1/info?format=json
  #  headers:
  #  - "NC-Token: $NEXTCLOUD_STATUS_TOKEN"
  - name: h5ai: files.ivyfanchiang.ca
    url: https://files.ivyfanchiang.ca

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.ivyfanchiang.ca
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Ivy's Upptime Status Page"
  introMessage:
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
